# Deploy master branch to EC2

name: Deploy prod

on:
  push:
    branches: [ master ]
  # Allows manual execution from Actions tab
  workflow_dispatch:

jobs:
  preserve:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Preserve old deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_URI_PROD }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          cd ${{ secrets.DEPLOYMENT_LOC }}
          cd ${{ secrets.DEPLOYMENT_URI_PROD }}
          ./cleanup.sh
    - name: Checkout new deployment
      uses: actions/checkout@master
    - name: Copy new deployment to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_URI_PROD }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        source: '.'
        target: ${{ secrets.DEPLOYMENT_LOC }}${{secrets.DEPLOYMENT_URI_PROD }}/public/
